neovim-bin = "/opt/homebrew/bin/nvim"
frame = "buttonless"
title-hidden = true

[font]
size = 14
normal = ["TX-02"]
# normal = { family = "IBM Plex Mono", style = "Regular" }
# bold = { family = "IBM Plex Mono", style = "Medium" }
# italic = { family = "IBM Plex Mono", style = "Italic" }
# bold_italic = { family = "IBM Plex Mono", style = "Medium Italic" }
