[colors]

# Default colors
[colors.primary]
background = "#FFFCF0"
foreground = "#100F0F"

# Cursor colors
[colors.cursor]
text = "#FFFCF0"
cursor = "#100F0F"

# Normal colors
[colors.normal]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

# Bright colors
[colors.bright]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

# Dim colors
[colors.dim]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"
