[terminal.shell]
program = "/usr/local/bin/fish"
args = ["-l", "-c", "zellij"]

[env]
TERM = "alacritty"
ALACRITTY = "true"

[window]
padding.x = 4
padding.y = 4
dynamic_padding = true
decorations = "Buttonless"
option_as_alt = "OnlyLeft"
# opacity = 0.9
# blur = true

[font]
# normal = { family = "BerkeleyMono Nerd Font" }
# normal = { family = "TX-02", style = "SemiLight" }
# bold = { family = "TX-02", style ="Medium" }
# italic = { family = "TX-02", style = "SemiLight Oblique"}
# bold_italic = { family = "TX-02", style = "Medium Oblique"}
# normal = { family = "JetbrainsMono Nerd Font" }
normal = { family = "BlexMono Nerd Font", style = "Regular" }
bold = { family = "BlexMono Nerd Font", style = "Medium" }
italic = { family = "BlexMono Nerd Font", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font", style = "Medium Italic" }
size = 14

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[general]
import = [
  "~/.config/alacritty/theme.toml",
  # "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/zellij-keybindings.toml",
  # "~/.config/alacritty/monaspace.toml",
]
